# Data Settings
phase: train

pickle_file_path: ./Dataset/ham10000/ham10000_train_test_names.pkl
snapshot_path: ./Results/

# Training Settings
epochs: 800
GPUs: [0]
num_workers: 8
batch_size: 8
save_freq: 20
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
ch: 32
ch_mult: [1,2,3,5]

# Optimizer Settings
lr: 0.002

# Loss Settings
w_rec: 1
w_dice: 1
w_ftv: 1
w_kl: 0.01
